package com.atguigu.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dep.did
     *
     * @mbggenerated Thu Apr 07 20:45:29 CST 2022
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dep.dname
     *
     * @mbggenerated Thu Apr 07 20:45:29 CST 2022
     */
    private String dname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dep.did
     *
     * @return the value of dep.did
     *
     * @mbggenerated Thu Apr 07 20:45:29 CST 2022
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dep.did
     *
     * @param did the value for dep.did
     *
     * @mbggenerated Thu Apr 07 20:45:29 CST 2022
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dep.dname
     *
     * @return the value of dep.dname
     *
     * @mbggenerated Thu Apr 07 20:45:29 CST 2022
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dep.dname
     *
     * @param dname the value for dep.dname
     *
     * @mbggenerated Thu Apr 07 20:45:29 CST 2022
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }
}